version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
    networks: 
      - sensor-network-dev
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/clickhouse-keeper:/etc/clickhouse-keeper
      - ./config/clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse-server/users.xml:/etc/clickhouse-server/users.xml
      - ./migrations:/migrations

volumes:
  clickhouse_data:

networks:
  sensor-network-dev:
    external: true
