{
 "title": "Kafka Cluster Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Broker Throughput in Records per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"sensor-logs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Throughput in Bytes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"sensor-logs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag by Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_lag_sum{consumergroup=\"sensor_group\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Throughput in Bytes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"sensor-logs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Brokers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{job=\"kafka-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Consumer in Consumer Group",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"sensor_group\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}