{
 "title": "Real-time Monitoring and Alerting in Industry Manufacturing",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "label": "Sensor Id",
    "query": "SELECT DISTINCT sensor_id\nFROM sensor_logs_db.sensor_logs;"
   },
   {
    "name": "product",
    "label": "Product",
    "query": "SELECT DISTINCT product\nFROM sensor_logs_db.sensor_logs;"
   },
   {
    "name": "data_center",
    "label": "Data Center",
    "query": "SELECT DISTINCT data_center\nFROM sensor_logs_db.sensor_logs;"
   }
  ]
 },
 "panels": [
  { "title": "Overall Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Health Percentage for Each Sensor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH sensor_stats AS (\r\n  SELECT\r\n    sensor_id,\r\n    count(*) AS total_count,\r\n    sum(if(status = 'Normal', 1, 0)) AS normal_count\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  GROUP BY sensor_id\r\n)\r\nSELECT\r\n  sensor_id,\r\n  (normal_count / CAST(total_count AS Float64)) * 100 AS percentage_normal\r\nFROM sensor_stats\r\nORDER BY sensor_id ASC"
    }
   ]
  },
  {
   "title": "Sensor Data Distribution by Status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH status_counts AS (\r\n  SELECT \r\n    sensor_id,\r\n    sum(if(status = 'Normal', 1, 0)) AS Normal,\r\n    sum(if(status = 'Critical', 1, 0)) AS Critical,\r\n    sum(if(status NOT IN ('Normal', 'Critical'), 1, 0)) AS Other\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  GROUP BY sensor_id\r\n)\r\nSELECT\r\n  sensor_id,\r\n  Normal,\r\n  Critical,\r\n  Other\r\nFROM status_counts\r\nORDER BY sensor_id ASC;\r\n"
    }
   ]
  },
  {
   "title": "Sensor-001 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_sensor_log AS (\r\n  SELECT \r\n\tJSONExtractString(metadata, 'machine_status') AS machine_status,\r\n\tmetadata\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE sensor_id = 'sensor-001'\r\n        AND $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT \r\n  machine_status AS \"Machine Status\",\r\n  CASE \r\n    WHEN machine_status = 'Start' THEN JSONExtractString(metadata, 'uptime')\r\n    WHEN machine_status = 'Stop'  THEN JSONExtractString(metadata, 'downtime')\r\n  END AS \"Status Time\"\r\nFROM latest_sensor_log;"
    }
   ]
  },
  {
   "title": "Sensor-002 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_sensor_log AS (\r\n  SELECT \r\n\tJSONExtractString(metadata, 'machine_status') AS machine_status,\r\n\tmetadata\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE sensor_id = 'sensor-002'\r\n        AND $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT \r\n  machine_status,\r\n  CASE \r\n    WHEN machine_status = 'Start' THEN JSONExtractString(metadata, 'uptime')\r\n    WHEN machine_status = 'Stop'  THEN JSONExtractString(metadata, 'downtime')\r\n  END AS metadata_time\r\nFROM latest_sensor_log;"
    }
   ]
  },
  {
   "title": "Sensor-003 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_sensor_log AS (\r\n  SELECT \r\n\tJSONExtractString(metadata, 'machine_status') AS machine_status,\r\n\tmetadata\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE sensor_id = 'sensor-003'\r\n        AND $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT \r\n  machine_status,\r\n  CASE \r\n    WHEN machine_status = 'Start' THEN JSONExtractString(metadata, 'uptime')\r\n    WHEN machine_status = 'Stop'  THEN JSONExtractString(metadata, 'downtime')\r\n  END AS metadata_time\r\nFROM latest_sensor_log;"
    }
   ]
  },
  {
   "title": "Sensor-004 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_sensor_log AS (\r\n  SELECT \r\n\tJSONExtractString(metadata, 'machine_status') AS machine_status,\r\n\tmetadata\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE sensor_id = 'sensor-004'\r\n        AND $__timeFilter(timestamp)\r\n        AND sensor_id IN ($sensor_id)\r\n        AND data_center IN ($data_center)\r\n        AND product IN ($product)\r\n  ORDER BY timestamp DESC\r\n  LIMIT 1\r\n)\r\nSELECT \r\n  machine_status,\r\n  CASE \r\n    WHEN machine_status = 'Start' THEN JSONExtractString(metadata, 'uptime')\r\n    WHEN machine_status = 'Stop'  THEN JSONExtractString(metadata, 'downtime')\r\n  END AS metadata_time\r\nFROM latest_sensor_log;"
    }
   ]
  },
  { "title": "Temperature Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Temperature Sensor Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  avg(measurement) AS \"Temperature\",\r\n  sensor_id\r\nFROM sensor_logs_db.sensor_logs\r\nWHERE \r\n  $__timeFilter(timestamp)\r\n  AND type = 'Temperature Sensor'\r\n  AND sensor_id IN ($sensor_id)\r\n  AND data_center IN ($data_center)\r\n  AND product IN ($product)\r\nGROUP BY time, sensor_id\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Temperature Sensor Statistics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n    AVG(measurement) AS \"Average Celsius\",\r\n    MAX(measurement) AS \"Maximum Celsius\",\r\n    MIN(measurement) AS \"Minimum Celsius\"\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE \r\n    $__timeFilter(timestamp)\r\n    AND type = 'Temperature Sensor'\r\n    AND sensor_id IN ($sensor_id)\r\n    AND data_center IN ($data_center)\r\n    AND product IN ($product)"
    }
   ]
  },
  { "title": "Electrical Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Electrical Sensor Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  avg(measurement) AS \"Electrical\",\r\n  sensor_id\r\nFROM sensor_logs_db.sensor_logs\r\nWHERE \r\n  $__timeFilter(timestamp)\r\n  AND type = 'Electrical Sensor'\r\n  AND sensor_id IN ($sensor_id)\r\n  AND data_center IN ($data_center)\r\n  AND product IN ($product)\r\nGROUP BY time, sensor_id\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Electrical Sensor Statistics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n    AVG(measurement) AS \"Average Ampere\",\r\n    MAX(measurement) AS \"Maximum Ampere\",\r\n    MIN(measurement) AS \"Minimum Ampere\"\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE \r\n    $__timeFilter(timestamp)\r\n    AND type = 'Electrical Sensor'\r\n    AND sensor_id IN ($sensor_id)\r\n    AND data_center IN ($data_center)\r\n    AND product IN ($product)"
    }
   ]
  },
  { "title": "Vibration Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Vibration Sensor Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  avg(measurement) AS \"Vibration\",\r\n  sensor_id\r\nFROM sensor_logs_db.sensor_logs\r\nWHERE \r\n  $__timeFilter(timestamp)\r\n  AND type = 'Vibration Sensor'\r\n  AND sensor_id IN ($sensor_id)\r\n  AND data_center IN ($data_center)\r\n  AND product IN ($product)\r\nGROUP BY time, sensor_id\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Vibration Sensor Statistics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n    AVG(measurement) AS \"Average Hz\",\r\n    MAX(measurement) AS \"Maximum Hz\",\r\n    MIN(measurement) AS \"Minimum Hz\"\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE \r\n    $__timeFilter(timestamp)\r\n    AND type = 'Vibration Sensor'\r\n    AND sensor_id IN ($sensor_id)\r\n    AND data_center IN ($data_center)\r\n    AND product IN ($product)"
    }
   ]
  },
  { "title": "Humidity Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Humidity Sensor Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  avg(measurement) AS \"Humidity\",\r\n  sensor_id\r\nFROM sensor_logs_db.sensor_logs\r\nWHERE \r\n  $__timeFilter(timestamp)\r\n  AND type = 'Humidity Sensor'\r\n  AND sensor_id IN ($sensor_id)\r\n  AND data_center IN ($data_center)\r\n  AND product IN ($product)\r\nGROUP BY time, sensor_id\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Humidity Sensor Statistics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n    AVG(measurement) AS \"Average Percentage\",\r\n    MAX(measurement) AS \"Maximum Percentage\",\r\n    MIN(measurement) AS \"Minimum Percentage\"\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE \r\n    $__timeFilter(timestamp)\r\n    AND type = 'Humidity Sensor'\r\n    AND sensor_id IN ($sensor_id)\r\n    AND data_center IN ($data_center)\r\n    AND product IN ($product)"
    }
   ]
  },
  { "title": "Pressure Sensor Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Pressure Sensor Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfMinute(timestamp) AS time,\r\n  avg(measurement) AS \"Pressure\",\r\n  sensor_id\r\nFROM sensor_logs_db.sensor_logs\r\nWHERE \r\n  $__timeFilter(timestamp)\r\n  AND type = 'Pressure Sensor'\r\n  AND sensor_id IN ($sensor_id)\r\n  AND data_center IN ($data_center)\r\n  AND product IN ($product)\r\nGROUP BY time, sensor_id\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Pressure Sensor Statistics",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT \r\n    AVG(measurement) AS \"Average Pascals\",\r\n    MAX(measurement) AS \"Maximum Pascals\",\r\n    MIN(measurement) AS \"Minimum Pascals\"\r\n  FROM sensor_logs_db.sensor_logs\r\n  WHERE \r\n    $__timeFilter(timestamp)\r\n    AND type = 'Pressure Sensor'\r\n    AND sensor_id IN ($sensor_id)\r\n    AND data_center IN ($data_center)\r\n    AND product IN ($product)"
    }
   ]
  }
 ]
}