version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sensor-network-dev
    ports:
      - "9090:9090"

networks:
  sensor-network-dev:
    external: true
