global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['host.docker.internal:9404']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['192.168.59.106:32404']
